// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// I18nColumns holds the columns for the "i18n" table.
	I18nColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "lang", Type: field.TypeString},
		{Name: "key", Type: field.TypeString},
		{Name: "raw", Type: field.TypeString},
		{Name: "created", Type: field.TypeInt64},
		{Name: "updated", Type: field.TypeInt64},
		{Name: "deleted", Type: field.TypeInt64, Nullable: true},
	}
	// I18nTable holds the schema information for the "i18n" table.
	I18nTable = &schema.Table{
		Name:       "i18n",
		Columns:    I18nColumns,
		PrimaryKey: []*schema.Column{I18nColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		I18nTable,
	}
)

func init() {
	I18nTable.Annotation = &entsql.Annotation{
		Table: "i18n",
	}
}
