// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/hiifong/i18n/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/hiifong/i18n/ent/enti18n"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// EntI18n is the client for interacting with the EntI18n builders.
	EntI18n *EntI18nClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.EntI18n = NewEntI18nClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:     ctx,
		config:  cfg,
		EntI18n: NewEntI18nClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:     ctx,
		config:  cfg,
		EntI18n: NewEntI18nClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		EntI18n.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.EntI18n.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.EntI18n.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *EntI18nMutation:
		return c.EntI18n.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// EntI18nClient is a client for the EntI18n schema.
type EntI18nClient struct {
	config
}

// NewEntI18nClient returns a client for the EntI18n from the given config.
func NewEntI18nClient(c config) *EntI18nClient {
	return &EntI18nClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `enti18n.Hooks(f(g(h())))`.
func (c *EntI18nClient) Use(hooks ...Hook) {
	c.hooks.EntI18n = append(c.hooks.EntI18n, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `enti18n.Intercept(f(g(h())))`.
func (c *EntI18nClient) Intercept(interceptors ...Interceptor) {
	c.inters.EntI18n = append(c.inters.EntI18n, interceptors...)
}

// Create returns a builder for creating a EntI18n entity.
func (c *EntI18nClient) Create() *EntI18nCreate {
	mutation := newEntI18nMutation(c.config, OpCreate)
	return &EntI18nCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of EntI18n entities.
func (c *EntI18nClient) CreateBulk(builders ...*EntI18nCreate) *EntI18nCreateBulk {
	return &EntI18nCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EntI18nClient) MapCreateBulk(slice any, setFunc func(*EntI18nCreate, int)) *EntI18nCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EntI18nCreateBulk{err: fmt.Errorf("calling to EntI18nClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EntI18nCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EntI18nCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for EntI18n.
func (c *EntI18nClient) Update() *EntI18nUpdate {
	mutation := newEntI18nMutation(c.config, OpUpdate)
	return &EntI18nUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EntI18nClient) UpdateOne(ei *EntI18n) *EntI18nUpdateOne {
	mutation := newEntI18nMutation(c.config, OpUpdateOne, withEntI18n(ei))
	return &EntI18nUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EntI18nClient) UpdateOneID(id int64) *EntI18nUpdateOne {
	mutation := newEntI18nMutation(c.config, OpUpdateOne, withEntI18nID(id))
	return &EntI18nUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for EntI18n.
func (c *EntI18nClient) Delete() *EntI18nDelete {
	mutation := newEntI18nMutation(c.config, OpDelete)
	return &EntI18nDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EntI18nClient) DeleteOne(ei *EntI18n) *EntI18nDeleteOne {
	return c.DeleteOneID(ei.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EntI18nClient) DeleteOneID(id int64) *EntI18nDeleteOne {
	builder := c.Delete().Where(enti18n.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EntI18nDeleteOne{builder}
}

// Query returns a query builder for EntI18n.
func (c *EntI18nClient) Query() *EntI18nQuery {
	return &EntI18nQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEntI18n},
		inters: c.Interceptors(),
	}
}

// Get returns a EntI18n entity by its id.
func (c *EntI18nClient) Get(ctx context.Context, id int64) (*EntI18n, error) {
	return c.Query().Where(enti18n.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EntI18nClient) GetX(ctx context.Context, id int64) *EntI18n {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *EntI18nClient) Hooks() []Hook {
	return c.hooks.EntI18n
}

// Interceptors returns the client interceptors.
func (c *EntI18nClient) Interceptors() []Interceptor {
	return c.inters.EntI18n
}

func (c *EntI18nClient) mutate(ctx context.Context, m *EntI18nMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EntI18nCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EntI18nUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EntI18nUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EntI18nDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown EntI18n mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		EntI18n []ent.Hook
	}
	inters struct {
		EntI18n []ent.Interceptor
	}
)
