// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hiifong/i18n/ent/enti18n"
	"github.com/hiifong/i18n/ent/predicate"
)

// EntI18nQuery is the builder for querying EntI18n entities.
type EntI18nQuery struct {
	config
	ctx        *QueryContext
	order      []enti18n.OrderOption
	inters     []Interceptor
	predicates []predicate.EntI18n
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EntI18nQuery builder.
func (eiq *EntI18nQuery) Where(ps ...predicate.EntI18n) *EntI18nQuery {
	eiq.predicates = append(eiq.predicates, ps...)
	return eiq
}

// Limit the number of records to be returned by this query.
func (eiq *EntI18nQuery) Limit(limit int) *EntI18nQuery {
	eiq.ctx.Limit = &limit
	return eiq
}

// Offset to start from.
func (eiq *EntI18nQuery) Offset(offset int) *EntI18nQuery {
	eiq.ctx.Offset = &offset
	return eiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (eiq *EntI18nQuery) Unique(unique bool) *EntI18nQuery {
	eiq.ctx.Unique = &unique
	return eiq
}

// Order specifies how the records should be ordered.
func (eiq *EntI18nQuery) Order(o ...enti18n.OrderOption) *EntI18nQuery {
	eiq.order = append(eiq.order, o...)
	return eiq
}

// First returns the first EntI18n entity from the query.
// Returns a *NotFoundError when no EntI18n was found.
func (eiq *EntI18nQuery) First(ctx context.Context) (*EntI18n, error) {
	nodes, err := eiq.Limit(1).All(setContextOp(ctx, eiq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{enti18n.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (eiq *EntI18nQuery) FirstX(ctx context.Context) *EntI18n {
	node, err := eiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EntI18n ID from the query.
// Returns a *NotFoundError when no EntI18n ID was found.
func (eiq *EntI18nQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = eiq.Limit(1).IDs(setContextOp(ctx, eiq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{enti18n.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (eiq *EntI18nQuery) FirstIDX(ctx context.Context) int64 {
	id, err := eiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EntI18n entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EntI18n entity is found.
// Returns a *NotFoundError when no EntI18n entities are found.
func (eiq *EntI18nQuery) Only(ctx context.Context) (*EntI18n, error) {
	nodes, err := eiq.Limit(2).All(setContextOp(ctx, eiq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{enti18n.Label}
	default:
		return nil, &NotSingularError{enti18n.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (eiq *EntI18nQuery) OnlyX(ctx context.Context) *EntI18n {
	node, err := eiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EntI18n ID in the query.
// Returns a *NotSingularError when more than one EntI18n ID is found.
// Returns a *NotFoundError when no entities are found.
func (eiq *EntI18nQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = eiq.Limit(2).IDs(setContextOp(ctx, eiq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{enti18n.Label}
	default:
		err = &NotSingularError{enti18n.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (eiq *EntI18nQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := eiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EntI18ns.
func (eiq *EntI18nQuery) All(ctx context.Context) ([]*EntI18n, error) {
	ctx = setContextOp(ctx, eiq.ctx, ent.OpQueryAll)
	if err := eiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EntI18n, *EntI18nQuery]()
	return withInterceptors[[]*EntI18n](ctx, eiq, qr, eiq.inters)
}

// AllX is like All, but panics if an error occurs.
func (eiq *EntI18nQuery) AllX(ctx context.Context) []*EntI18n {
	nodes, err := eiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EntI18n IDs.
func (eiq *EntI18nQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if eiq.ctx.Unique == nil && eiq.path != nil {
		eiq.Unique(true)
	}
	ctx = setContextOp(ctx, eiq.ctx, ent.OpQueryIDs)
	if err = eiq.Select(enti18n.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (eiq *EntI18nQuery) IDsX(ctx context.Context) []int64 {
	ids, err := eiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (eiq *EntI18nQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, eiq.ctx, ent.OpQueryCount)
	if err := eiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, eiq, querierCount[*EntI18nQuery](), eiq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (eiq *EntI18nQuery) CountX(ctx context.Context) int {
	count, err := eiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (eiq *EntI18nQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, eiq.ctx, ent.OpQueryExist)
	switch _, err := eiq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (eiq *EntI18nQuery) ExistX(ctx context.Context) bool {
	exist, err := eiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EntI18nQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (eiq *EntI18nQuery) Clone() *EntI18nQuery {
	if eiq == nil {
		return nil
	}
	return &EntI18nQuery{
		config:     eiq.config,
		ctx:        eiq.ctx.Clone(),
		order:      append([]enti18n.OrderOption{}, eiq.order...),
		inters:     append([]Interceptor{}, eiq.inters...),
		predicates: append([]predicate.EntI18n{}, eiq.predicates...),
		// clone intermediate query.
		sql:  eiq.sql.Clone(),
		path: eiq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Lang string `json:"lang,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EntI18n.Query().
//		GroupBy(enti18n.FieldLang).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (eiq *EntI18nQuery) GroupBy(field string, fields ...string) *EntI18nGroupBy {
	eiq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EntI18nGroupBy{build: eiq}
	grbuild.flds = &eiq.ctx.Fields
	grbuild.label = enti18n.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Lang string `json:"lang,omitempty"`
//	}
//
//	client.EntI18n.Query().
//		Select(enti18n.FieldLang).
//		Scan(ctx, &v)
func (eiq *EntI18nQuery) Select(fields ...string) *EntI18nSelect {
	eiq.ctx.Fields = append(eiq.ctx.Fields, fields...)
	sbuild := &EntI18nSelect{EntI18nQuery: eiq}
	sbuild.label = enti18n.Label
	sbuild.flds, sbuild.scan = &eiq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EntI18nSelect configured with the given aggregations.
func (eiq *EntI18nQuery) Aggregate(fns ...AggregateFunc) *EntI18nSelect {
	return eiq.Select().Aggregate(fns...)
}

func (eiq *EntI18nQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range eiq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, eiq); err != nil {
				return err
			}
		}
	}
	for _, f := range eiq.ctx.Fields {
		if !enti18n.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if eiq.path != nil {
		prev, err := eiq.path(ctx)
		if err != nil {
			return err
		}
		eiq.sql = prev
	}
	return nil
}

func (eiq *EntI18nQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EntI18n, error) {
	var (
		nodes = []*EntI18n{}
		_spec = eiq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EntI18n).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EntI18n{config: eiq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, eiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (eiq *EntI18nQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := eiq.querySpec()
	_spec.Node.Columns = eiq.ctx.Fields
	if len(eiq.ctx.Fields) > 0 {
		_spec.Unique = eiq.ctx.Unique != nil && *eiq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, eiq.driver, _spec)
}

func (eiq *EntI18nQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(enti18n.Table, enti18n.Columns, sqlgraph.NewFieldSpec(enti18n.FieldID, field.TypeInt64))
	_spec.From = eiq.sql
	if unique := eiq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if eiq.path != nil {
		_spec.Unique = true
	}
	if fields := eiq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, enti18n.FieldID)
		for i := range fields {
			if fields[i] != enti18n.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := eiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := eiq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := eiq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := eiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (eiq *EntI18nQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(eiq.driver.Dialect())
	t1 := builder.Table(enti18n.Table)
	columns := eiq.ctx.Fields
	if len(columns) == 0 {
		columns = enti18n.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if eiq.sql != nil {
		selector = eiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if eiq.ctx.Unique != nil && *eiq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range eiq.predicates {
		p(selector)
	}
	for _, p := range eiq.order {
		p(selector)
	}
	if offset := eiq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := eiq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EntI18nGroupBy is the group-by builder for EntI18n entities.
type EntI18nGroupBy struct {
	selector
	build *EntI18nQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (eigb *EntI18nGroupBy) Aggregate(fns ...AggregateFunc) *EntI18nGroupBy {
	eigb.fns = append(eigb.fns, fns...)
	return eigb
}

// Scan applies the selector query and scans the result into the given value.
func (eigb *EntI18nGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, eigb.build.ctx, ent.OpQueryGroupBy)
	if err := eigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EntI18nQuery, *EntI18nGroupBy](ctx, eigb.build, eigb, eigb.build.inters, v)
}

func (eigb *EntI18nGroupBy) sqlScan(ctx context.Context, root *EntI18nQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(eigb.fns))
	for _, fn := range eigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*eigb.flds)+len(eigb.fns))
		for _, f := range *eigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*eigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := eigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EntI18nSelect is the builder for selecting fields of EntI18n entities.
type EntI18nSelect struct {
	*EntI18nQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (eis *EntI18nSelect) Aggregate(fns ...AggregateFunc) *EntI18nSelect {
	eis.fns = append(eis.fns, fns...)
	return eis
}

// Scan applies the selector query and scans the result into the given value.
func (eis *EntI18nSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, eis.ctx, ent.OpQuerySelect)
	if err := eis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EntI18nQuery, *EntI18nSelect](ctx, eis.EntI18nQuery, eis, eis.inters, v)
}

func (eis *EntI18nSelect) sqlScan(ctx context.Context, root *EntI18nQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(eis.fns))
	for _, fn := range eis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*eis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := eis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
