// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/hiifong/i18n/ent/enti18n"
	"github.com/hiifong/i18n/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	enti18nFields := schema.EntI18n{}.Fields()
	_ = enti18nFields
	// enti18nDescCreated is the schema descriptor for created field.
	enti18nDescCreated := enti18nFields[4].Descriptor()
	// enti18n.DefaultCreated holds the default value on creation for the created field.
	enti18n.DefaultCreated = enti18nDescCreated.Default.(func() int64)
	// enti18nDescUpdated is the schema descriptor for updated field.
	enti18nDescUpdated := enti18nFields[5].Descriptor()
	// enti18n.DefaultUpdated holds the default value on creation for the updated field.
	enti18n.DefaultUpdated = enti18nDescUpdated.Default.(func() int64)
	// enti18n.UpdateDefaultUpdated holds the default value on update for the updated field.
	enti18n.UpdateDefaultUpdated = enti18nDescUpdated.UpdateDefault.(func() int64)
}
